services:
  proxy-cache-server:
    build: .
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - proxy-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
