name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up pnpm
      uses: pnpm/action-setup@v2

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm run build

    - name: Verify build output
      run: ls -la dist

    - name: Create package
      run: pnpm run package

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Tag
        run: |
          VERSION=$(date +'%Y.%m.%d.%H.%M.%S')
          git tag -a "v$VERSION" -m "Release $VERSION"
          git push origin "v$VERSION"

      - name: Set up GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}