name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up pnpm
      uses: pnpm/action-setup@v2

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm build

    - name: Create package
      run: pnpm package

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*
            build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
